### ISSUE TITLE
修改之后卡在登录页面

### ISSUE THREAD

**Issue by SquareLeo** [msojocs/fiddler-everywhere-crack#3]
3.3.0版本覆盖main.***.js 文件与两个dl文件之后，重新打开卡在登录页面，麻烦大佬帮忙瞅瞅这个怎么解决
![image](https://user-images.githubusercontent.com/15210176/178400140-d150e4a2-0e7b-40db-8309-249505ffbb86.png)

**Comment by msojocs** [comment]
你的网络可能有点问题

**Comment by littleheary** [comment]
我修改完以后也是卡在这个页面不动了。

**Comment by littleheary** [comment]
登录失败的错误信息如下：
[2022-07-16 00:07:41:995] [Error] [NETCore] Unexpected backend error.
System.MissingMethodException: Method not found: 'Boolean <>c__DisplayClass18_0.<GetBestAccount>b__0(FiddlerBackend.Contracts.UserAccountDTO)'.
   at FiddlerBackendSDK.User.UserClient.GetBestAccount(UserWithBestAccountDTO user)
   at Fiddler.WebUi.Services.Backend.BackendService.SetUserInfo(Boolean emitLicenseChange, Boolean isManuallyRequested)
   at Fiddler.WebUi.Services.Backend.BackendService.<>c__DisplayClass65_0.<<Login>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Fiddler.WebUi.Services.Backend.BackendService.ExecuteWithSdkErrorsHandling[T](Func`1 action)
[2022-07-16 00:07:41:995] [Error] [NETCore] Failed to invoke hub method 'Login'.
Microsoft.AspNetCore.SignalR.HubException: Unexpected backend error.
   at Fiddler.WebUi.Services.Backend.BackendService.ExecuteWithSdkErrorsHandling[T](Func`1 action)
   at Fiddler.WebUi.Services.Backend.BackendService.Login(String apiUrl, String paymentUrl, String idToken, String installationId)
   at Fiddler.WebUi.Services.Users.UsersService.Login(EnvironmentInfo environmentInfo, UserProfile userProfile, TabsState persistedTabsState)
   at Fiddler.WebUi.Hubs.FiddlerHub.Login(EnvironmentInfo environmentInfo, UserProfile userProfile, TabsState persistedTabsState)
   at lambda_method9(Closure , Object )
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|16_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
[2022-07-16 00:07:41:998] [Information] [Angular] Backend login failed.

C:\Users\Lenovo\AppData\Roaming\Fiddler Everywhere\Logs\netcore.log

**Comment by littleheary** [comment]
登录失败的错误信息如下：
[2022-07-16 00:07:41:995] [Error] [NETCore] Unexpected backend error.
System.MissingMethodException: Method not found: 'Boolean <>c__DisplayClass18_0.<GetBestAccount>b__0(FiddlerBackend.Contracts.UserAccountDTO)'.
   at FiddlerBackendSDK.User.UserClient.GetBestAccount(UserWithBestAccountDTO user)
   at Fiddler.WebUi.Services.Backend.BackendService.SetUserInfo(Boolean emitLicenseChange, Boolean isManuallyRequested)
   at Fiddler.WebUi.Services.Backend.BackendService.<>c__DisplayClass65_0.<<Login>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Fiddler.WebUi.Services.Backend.BackendService.ExecuteWithSdkErrorsHandling[T](Func`1 action)
[2022-07-16 00:07:41:995] [Error] [NETCore] Failed to invoke hub method 'Login'.
Microsoft.AspNetCore.SignalR.HubException: Unexpected backend error.
   at Fiddler.WebUi.Services.Backend.BackendService.ExecuteWithSdkErrorsHandling[T](Func`1 action)
   at Fiddler.WebUi.Services.Backend.BackendService.Login(String apiUrl, String paymentUrl, String idToken, String installationId)
   at Fiddler.WebUi.Services.Users.UsersService.Login(EnvironmentInfo environmentInfo, UserProfile userProfile, TabsState persistedTabsState)
   at Fiddler.WebUi.Hubs.FiddlerHub.Login(EnvironmentInfo environmentInfo, UserProfile userProfile, TabsState persistedTabsState)
   at lambda_method9(Closure , Object )
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<Invoke>g__ExecuteInvocation|16_0(DefaultHubDispatcher`1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)
[2022-07-16 00:07:41:998] [Information] [Angular] Backend login failed.

C:\Users\Lenovo\AppData\Roaming\Fiddler Everywhere\Logs\netcore.log

**Comment by msojocs** [comment]
@littleheary 你是不是把b___0方法删除了？
